@isTest
public  class AP1_ExecuteBatch_Test {
      public static testMethod void  lancerBatchTest(){
        AP1_ExecuteBatch.runBatchCreationRequete();
        AP1_ExecuteBatch.runBatchPrecodage();
        AP1_ExecuteBatch.runBatchRecuperationRdv();
        AP1_ExecuteBatch.runBatchShareNote();
        AP1_ExecuteBatch.runBatchCtrAband();
        AP1_ExecuteBatch.runBatchRemiseSolde();
        AP1_ExecuteBatch.runBatchCreditExcep();
        AP1_ExecuteBatch.runBatchDelEven();
		AP1_ExecuteBatch.runBatch021();
        AP1_ExecuteBatch.runBatchCloseCase009();
        AP1_ExecuteBatch.runBatch017();
        AP1_ExecuteBatch.runBatch014();
        AP1_ExecuteBatch.runBatch025inactif();
        AP1_ExecuteBatch.runBatch025majetiq();
         AP1_ExecuteBatch.runBatch010(); 
          AP1_ExecuteBatch.runBatch022RM();
          AP1_ExecuteBatch.runBatch026();
          AP1_ExecuteBatch.runBatch010();
      } 
    
            
          
    
}